language: ruby
bundler_args: --without development
rvm:
  - 2.2.2
  - jruby-head
  - rbx-2
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: rbx-2
  exclude:
    - rvm: jruby-head
      os: osx
    - rvm: rbx-2
      os: osx
os:
  - linux
  - osx
osx_image: xcode7.1
env:
  # TODO: 0.8 is enough on Linux, but 2 seems needed for Travis/OSX
  - LISTEN_TESTS_DEFAULT_LAG=2
sudo: false
